CREATE TABLE YOGA_CLASS (ID BIGINT NOT NULL AUTO_INCREMENT, CLASSNAME VARCHAR(100), LASTUPDATED TIMESTAMP, PUBLICSHARED BIGINT, YOGATEACHER_NAME VARCHAR(25), YOGATEACHER_EMAIL_ID VARCHAR(25), CONSTRAINT classid_pk PRIMARY KEY (ID));
CREATE TABLE YOGA_TEACHER (LASTUPDATED TIMESTAMP, TEACHERNAME VARCHAR(25) NOT NULL, EMAILID VARCHAR(25) NOT NULL, CONSTRAINT teacherid_pk PRIMARY KEY (TEACHERNAME, EMAILID));
CREATE TABLE YOGA_POSE (ID BIGINT NOT NULL AUTO_INCREMENT, IMAGEPATH VARCHAR(100), LASTUPDATED TIMESTAMP, POSEDESCRIPTION VARCHAR(100), POSENAME VARCHAR(100), CONSTRAINT poseid_pk PRIMARY KEY (ID));
CREATE TABLE YOGA_POSE_CATEGORY (POSECATEGORYNAME VARCHAR(25) NOT NULL, LASTUPDATED TIMESTAMP,  CONSTRAINT categoryname_pk PRIMARY KEY (POSECATEGORYNAME));
CREATE TABLE YOGA_CLASS_POSES (YOGA_CLASS_ID BIGINT NOT NULL, YOGA_POSE_ID BIGINT NOT NULL, CONSTRAINT classid_poseid_pk PRIMARY KEY (YOGA_CLASS_ID, YOGA_POSE_ID));
CREATE TABLE YOGA_POSE_CATEGORIES (YOGA_POSE_ID BIGINT NOT NULL, POSE_CATEGORY_NAME VARCHAR(25) NOT NULL, CONSTRAINT poseid_categoryid_pk PRIMARY KEY (YOGA_POSE_ID, POSE_CATEGORY_NAME));
ALTER TABLE YOGA_CLASS ADD CONSTRAINT FK_YOGA_CLASS_YOGATEACHER_NAME FOREIGN KEY (YOGATEACHER_NAME, YOGATEACHER_EMAIL_ID) REFERENCES YOGA_TEACHER (TEACHERNAME, EMAILID);
ALTER TABLE YOGA_CLASS_POSES ADD CONSTRAINT FK_YOGA_CLASS_POSES_YOGA_POSE_ID FOREIGN KEY (YOGA_POSE_ID) REFERENCES YOGA_POSE (ID);
ALTER TABLE YOGA_CLASS_POSES ADD CONSTRAINT FK_YOGA_CLASS_POSES_YOGA_CLASS_ID FOREIGN KEY (YOGA_CLASS_ID) REFERENCES YOGA_CLASS (ID);
ALTER TABLE YOGA_POSE_CATEGORIES ADD CONSTRAINT FK_YOGA_POSE_CATEGORIES_YOGA_POSE_ID FOREIGN KEY (YOGA_POSE_ID) REFERENCES YOGA_POSE (ID);
ALTER TABLE YOGA_POSE_CATEGORIES ADD CONSTRAINT FK_YOGA_POSE_CATEGORIES_POSE_CATEGORY_NAME FOREIGN KEY (POSE_CATEGORY_NAME) REFERENCES YOGA_POSE_CATEGORY (POSECATEGORYNAME);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT BIGINT, PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

-- insert default data
INSERT IGNORE INTO YOGA_TEACHER(EMAILID, TEACHERNAME, LASTUPDATED) VALUES('teacher@email.com', 'Default Yoga Teacher', NOW());