-- Drop schema script
ALTER TABLE YOGA_CLASS_POSES DROP CONSTRAINT FK_YOGA_CLASS_POSES_YOGA_POSE_ID;
ALTER TABLE YOGA_CLASS_POSES DROP CONSTRAINT FK_YOGA_CLASS_POSES_YOGA_CLASS_ID;
ALTER TABLE YOGA_TEACHER_CLASSES DROP CONSTRAINT FK_YOGA_TEACHER_CLASSES_YOGA_TEACHER_ID;
ALTER TABLE YOGA_TEACHER_CLASSES DROP CONSTRAINT FK_YOGA_TEACHER_CLASSES_YOGA_CLASS_ID;
ALTER TABLE YOGA_POSE_CATEGORIES DROP CONSTRAINT FK_YOGA_POSE_CATEGORIES_YOGA_POSE_ID;
ALTER TABLE YOGA_POSE_CATEGORIES DROP CONSTRAINT FK_YOGA_POSE_CATEGORIES_POSE_CATEGORY_NAME;
DROP TABLE YOGA_CLASS;
DROP TABLE YOGA_TEACHER;
DROP TABLE YOGA_POSE;
DROP TABLE YOGA_POSE_CATEGORY;
DROP TABLE YOGA_CLASS_POSES;