CREATE TABLE YOGA_CLASS (ID BIGINT NOT NULL, CLASSNAME VARCHAR(25), PUBLICSHARED TINYINT, CONSTRAINT classid_pk PRIMARY KEY (ID));
CREATE TABLE YOGA_TEACHER (ID BIGINT NOT NULL, TEACHERNAME VARCHAR(25), CONSTRAINT teacher_pk PRIMARY KEY (ID));
CREATE TABLE YOGA_POSE (ID BIGINT NOT NULL, IMAGEPATH VARCHAR(100), POSEDESCRIPTION VARCHAR(1), POSENAME VARCHAR(1), CONSTRAINT poseid_pk PRIMARY KEY (ID));
CREATE TABLE YOGA_POSE_CATEGORY (ID BIGINT NOT NULL, POSECATEGORYNAME VARCHAR(25), CONSTRAINT categoryid_pk PRIMARY KEY (ID));
CREATE TABLE YOGA_CLASS_POSES (YOGA_CLASS_ID BIGINT NOT NULL, YOGA_POSE_ID BIGINT NOT NULL, CONSTRAINT classid_poseid_pk PRIMARY KEY (YOGA_CLASS_ID, YOGA_POSE_ID));
CREATE TABLE YOGA_TEACHER_CLASSES (YOGA_TEACHER_ID BIGINT NOT NULL, YOGA_CLASS_ID BIGINT NOT NULL, CONSTRAINT teacherid_classid_pk PRIMARY KEY (YOGA_TEACHER_ID, YOGA_CLASS_ID));
CREATE TABLE YOGA_POSE_CATEGORIES (YOGA_POSE_ID BIGINT NOT NULL, POSE_CATEGORY_ID BIGINT NOT NULL, CONSTRAINT poseid_categoryid_pk PRIMARY KEY (YOGA_POSE_ID, POSE_CATEGORY_ID));
ALTER TABLE YOGA_CLASS_POSES ADD CONSTRAINT FK_YOGA_CLASS_POSES_YOGA_POSE_ID FOREIGN KEY (YOGA_POSE_ID) REFERENCES YOGA_POSE (ID);
ALTER TABLE YOGA_CLASS_POSES ADD CONSTRAINT FK_YOGA_CLASS_POSES_YOGA_CLASS_ID FOREIGN KEY (YOGA_CLASS_ID) REFERENCES YOGA_CLASS (ID);
ALTER TABLE YOGA_TEACHER_CLASSES ADD CONSTRAINT FK_YOGA_TEACHER_CLASSES_YOGA_TEACHER_ID FOREIGN KEY (YOGA_TEACHER_ID) REFERENCES YOGA_TEACHER (ID);
ALTER TABLE YOGA_TEACHER_CLASSES ADD CONSTRAINT FK_YOGA_TEACHER_CLASSES_YOGA_CLASS_ID FOREIGN KEY (YOGA_CLASS_ID) REFERENCES YOGA_CLASS (ID);
ALTER TABLE YOGA_POSE_CATEGORIES ADD CONSTRAINT FK_YOGA_POSE_CATEGORIES_POSE_CATEGORY_ID FOREIGN KEY (POSE_CATEGORY_ID) REFERENCES YOGA_POSE_CATEGORY (ID);
ALTER TABLE YOGA_POSE_CATEGORIES ADD CONSTRAINT FK_YOGA_POSE_CATEGORIES_YOGA_POSE_ID FOREIGN KEY (YOGA_POSE_ID) REFERENCES YOGA_POSE (ID);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(19), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);

